---

db:
  image: postgres
  volumes:
    - ./db/data/:/var/lib/postgresql/data/

redis:
  image: redis

worker:
  image: rails-app
  command: bundle exec sidekiq -C config/sidekiq.yml
  volumes:
    - ./app/:/usr/src/app
  links:
    - db
    - redis
  env_file:
    - .env

web:
  image: rails-app
  command: bundle exec thin start --rackup config.ru --port 3000
  volumes:
    - ./app/:/usr/src/app
  links:
    - db
    - redis
  ports:
    - "3030:3000"
  env_file:
    - .env
